name: aisits_mobileApp
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  test: ^1.25.8
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  http: ^1.0.0
  web_socket_channel: ^3.0.2
  socket_io_client: ^3.0.2
  flutter_svg: ^2.0.17
  flutter_map_marker_cluster: ^1.3.6
  async: ^2.10.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
 


flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/ship.json
  - assets/icons/cargo.svg
  - assets/icons/cruise.svg
  - assets/icons/special.svg
  - assets/icons/support.svg
  - assets/icons/tanker.svg
  - assets/icons/unknown.svg